port: 3000
db:
  host: localhost
  port: 5432
  user: user_svc
  password: user_svc
  database: user_svc
  ssl: false
jwt:
  secret: secret
  accessTokenTTL: 15m
  refreshTokenTTL: 7d
events:
  url: 0.0.0.0:5002